export const baseUrl = 'https://rentafi-production-yvj5gszdhq-an.a.run.app';
export const vaultAbi = [
  'function wrapContract() view returns (address)',
  'function originalCollection() view returns (address)',
  'function marketContract() view returns (address)',
  'function collectionOwner() view returns (address)',
  'function minDuration() view returns (uint256)',
  'function maxDuration() view returns (uint256)',
  'function collectionOwnerFeeRatio() view returns (uint256)',
  'function originalName() view returns (string memory)',
  'function originalSymbol() view returns (string memory)',
  'function allTokenIdAllowed() view returns (uint256)',
  'function payoutAddress() view returns (address)',
  'function getPaymentTokens() view returns (address[])',
  'function getTokenIdAllowed(uint256 tokenId) view returns (uint256)',
  'function minPrices(address paymentToken) view returns (uint256)',
  'function setMinPrices(uint256[] memory minPrices, address[] memory paymentTokens)',
  'function setCollectionOwnerFeeRatio(uint256 feeRatio)',
  'function setPayoutAddress(address payoutAddress)',
  'function setDuration(uint256 minDuration, uint256 maxDuration)',
  'function setTokenIdAllowed(uint256[] calldata tokenIds, uint256[] calldata allowed)',
];
